title: "cat-repo-auditor"
description: "cat-repo-auditor"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/cat-repo-auditor
plugins:
  - jekyll-sitemap
